<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TradeBot.Bot</RootNamespace>
    <AssemblyName>tradebot</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../crypto-trading-bot.Engine/crypto-trading-bot.Engine.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
